version: '3.8'
services:
  app:
    image: socialnetwork-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socialnetwork-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=SUA_CHAVE_SECRETA_AQUI_DEVE_SER_BEM_LONGA_E_ALEATORIA
      - JWT_EXPIRATION=86400000

  db:
    image: postgres:16
    container_name: socialnetwork-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: