server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

file.upload-dir=./uploads

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=${JWT_SECRET:chave_secreta_padrao_para_desenvolvimento_local}
jwt.expiration=${JWT_EXPIRATION:86400000}

logging.level.root=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.example.socialnetwork=DEBUG