# Propriedade para o FileStorageService
file.upload-dir=./target/test-uploads

# Propriedades para o JwtTokenUtil
jwt.secret=a-very-long-and-random-secret-key-for-testing-purposes-that-is-at-least-256-bits
jwt.expiration=3600000